server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/j0812?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2b8
    username: root
    password: 123456
    druid:
      max-active: 10
      min-idle: 5
      max-wait: 5000
      initial-size: 5
      validation-query: select 1
      stat-view-servlet:
        enabled: false
        login-username: admin
        login-password: admin
        allow:
        deny:
        url-pattern: "/druid/*"
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml